### ISSUE TITLE
Mapa - vnutrobloky

### ISSUE THREAD

**Issue by Zanarova** [bratislava/paas-mpa#189]
Testfligt - build 1

steps to reproduce: 
- put pin on unregulated zone (Pokrok - vnútroblok)
- I´m able to buy ticket

Expected results: 
- pin on vnutroblok should be dissabled, because vnutrobloky are for residental parking - they are unregulated for now.

![Image](https://github.com/bratislava/paas-mpa/assets/108303461/5e3e91f0-dc82-4113-9e2d-e9847b22b04a)

**Comment by radoslavzeman** [comment]
Bude sa riesit na urovni GIS dat.
