### ISSUE TITLE
Download receipt of purchased ticket

### ISSUE THREAD

**Issue by Zanarova** [bratislava/paas-mpa#194]
As a user I want to share PDR receipt of purchased ticket (after being terminated or finished) 

Figma: https://www.figma.com/file/3TppNabuUdnCChkHG9Vft7/paas-mpa?type=design&node-id=43-882&mode=design&t=j6PsmSQ14VxuVFCM-0

Content of the receipt: 

[Receipt.pdf](https://github.com/bratislava/paas-mpa/files/13460344/Receipt.pdf)

**Comment by PavelFilo** [comment]
FE is done, task is waiting for API (hidden more icon till then) related issue:  #325
