### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/paas-mpa#233]
https://www.figma.com/file/3TppNabuUdnCChkHG9Vft7/paas-mpa?type=design&node-id=5899-24312&mode=design&t=CVMKiyAna7GP1RaW-0

**Comment by Zanarova** [comment]
Final app icon: https://www.figma.com/file/3TppNabuUdnCChkHG9Vft7/paas-mpa?type=design&node-id=7602-9377&mode=design&t=rRLclPtgHI4so63L-0
