### ISSUE TITLE
Body mapa: detail úseku

### ISSUE THREAD

**Issue by Zanarova** [bratislava/paas-mpa#259]
Kroky:
- click na bod
- zobrazí sa bottom sheet
- názov v hlavičke je ,,detail bodu,, alebo ,,point detail,,

Želaný stav
Zmena ,,detail bodu,, na kategóriu bodu napr: parkomat, partnerská prevádzka a pod.

![Image](https://github.com/bratislava/paas-mpa/assets/108303461/7fc90ca2-d85b-4034-a9a9-07a2d32d9b3a)

![Image](https://github.com/bratislava/paas-mpa/assets/108303461/47f4b2bb-a4d6-4131-ada1-9fe994f9dfeb)

**Comment by Zanarova** [comment]
Hello skúšam na verzií 1.0.5. (23) ale stále sa zobrazuje text pod btn. Presúvam do stavu To do. 

![Image](https://github.com/bratislava/paas-mpa/assets/108303461/5ee6ed51-b671-4933-b2d0-275d228b0d2b)

**Comment by radoslavzeman** [comment]
@Zanarova prosim testovat len co je v scope tasku. V tomto pripade task hovori:
> Želaný stav
> Zmena ,,detail bodu,, na kategóriu bodu napr: parkomat, partnerská prevádzka a pod.

Co ty spominas "stále sa zobrazuje text pod btn", co s tymto taskom nesuvisi.
