### ISSUE TITLE
Texty pre vsetky usecases na skracovanie listka

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/paas-mpa#323]
Ide o tento screen: https://www.figma.com/file/3TppNabuUdnCChkHG9Vft7/paas-mpa?node-id=7743%3A4597&mode=dev

**Comment by Zanarova** [comment]
Zobrazovať budeme na začiatku jeden všeobecný screen s use cases o ktorých vieme, po spustení aplikácie budeme sledovať aké iné use casy vedia nastať. Po vychytaní všetkých UC zobrazíme userovi iba to čo sa ho týka:

Všeobecný text: 
Skrátenie parkovacieho lístka je možné za splnenia určitých podmienok, ktoré upravuje [Prevádzkový poriadok dočasného parkovania motorových vozidiel v hlavnom meste SR Bratislave] (https://paas.sk/wp-content/uploads/2023/12/Prevadzkovy-poriadok-PP_v2.15.pdf) 

**Základné podmienky:**
- skrátenie lístka je možné vykonať po uplynutí 15 minút od začiatku platnosti lístka. V prípade že lístok skrátite skôr, bude lístok ukončený až po uplynutí doby 15 minút. (neplatí ak bol lístok zakúpený výhradne cez Bonusovú alebo Návštevnícku parkovaciu kartu)
- lístok je možné skrátit´ za storno poplatok vo výške 0,05€ (neplatí ak bol lístok zakúpený výhradne cez Návštevnícku alebo Bonusovú kartu.)
- V prípade okamžitého skrátenia lístka zakúpeného výhradne cez Bonusovú parkovaciu kartu bude z parkovacej karty odčítaná celá minúta
- V prípade predĺženia parkovacieho lístka, bude umožnené skrátiť posledné predĺženie lístka

**Comment by Zanarova** [comment]
EN: 
The shortening of a parking ticket is possible under certain conditions regulated by the [Operating Order for Temporary Parking of Motor Vehicles in the capital city of the Slovak Republic, Bratislava] (https://paas.sk/wp-content/uploads/2023/12/Operating-Order-PP_v2.15.pdf).

**Main conditions:**
- Shortening the ticket is possible after 15 minutes have elapsed from the start of the ticket's validity. If you shorten the ticket earlier, the ticket will only be terminated after the expiration of the 15-minute period. (This does not apply if the ticket was purchased exclusively through the Bonus or Visitor Parking Card.)
- The ticket can be shortened for a cancellation fee of €0.05 (This does not apply if the ticket was purchased exclusively through the Visitor or Bonus Card.)
- In the case of immediate shortening of a ticket purchased exclusively through the Bonus Parking Card, a full minute will be deducted from the parking card.
- In the case of extending a parking ticket, it will be possible to shorten the last extension.
