### ISSUE TITLE
Mapa: presun pinu na zvolený úsek v search

### ISSUE THREAD

**Issue by Zanarova** [bratislava/paas-mpa#332]
Version 1.0.5. (17) staging
deje sa iba na iOS

Kroky:
- click na search
- vypíš úsek napr. Miletičová
- click na úsek
- pin zostane na rovnakom mieste

https://github.com/bratislava/paas-mpa/assets/108303461/ec11b60d-a067-4909-921a-fcf8b10d7d2e

Želaný stav:
- zobraz pin na zvolenom úseku zo search

**Comment by lukybil** [comment]
Nepodarilo sa mi zreprodukovat na Androide.

**Comment by marykosticka** [comment]
@Zanarova tiež som skúšala a mne sa pin pekne hýbe podľa toho, akú zvolím ulicu / zónu

**Comment by Zanarova** [comment]
@lukybil apparently sa toto deje iba na mojom zariadení iOS s operačnou verziou systému 16.1.1 - ostatným kolegom ktorí majú novšiu verziu sa to nedeje. Skúsme dať tento task on hold a keď pushneme novú verziu ktorú si stiahnem budem sledovať či sa to opakuje.

**Comment by radoslavzeman** [comment]
@Zanarova vies prosim pretestovat? :)

**Comment by Zanarova** [comment]
Testila som opäť na mojom zariadení Iphone 13 mini s operačnou verziou systému 16.1.1 nehodí ma na zvolenú adresu:


https://github.com/bratislava/paas-mpa/assets/108303461/8236af3e-5d85-41fe-8e2f-70e146c6d19c
