### ISSUE TITLE
Correctly refetch active tickets count in bottom sheet top attachment

### ISSUE THREAD

**Issue by lukybil** [bratislava/paas-mpa#338]

**Comment by Zanarova** [comment]
Ahojte @PavelFilo kupujem lístky a zobrazuje mi dobrý počet, neviem ešte skracovať tak neviem otestiť či to beží aj pri skrátení. Zajtra by malo byť skrátenie done tak viem to aj pri tomto use case otestovať. Neviem aké všetky use casy boli v scope tohto issue tak radšej nechcem ukončovať task. :)
