### ISSUE TITLE
Login screen missing top padding

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/paas-mpa#358]
Title is too close to top. According to Figma there should be Back arrow. https://www.figma.com/file/3TppNabuUdnCChkHG9Vft7/paas-mpa?node-id=1%3A5&mode=dev

![Image](https://github.com/bratislava/paas-mpa/assets/19418224/b6a3626c-5b3c-40f9-b094-1a17fb2231a2)

**Comment by PavelFilo** [comment]
Back button is there only after onboarding, but padding should be there

**Comment by radoslavzeman** [comment]
@PavelFilo tu tiež, dole.

![Screenshot_20240115_151831_com bratislava paas](https://github.com/bratislava/paas-mpa/assets/19418224/facef480-d16a-4b7d-a350-c5ce15d974a4)
