### ISSUE TITLE
Bottom sheet: point detail

### ISSUE THREAD

**Issue by Zanarova** [bratislava/paas-mpa#419]
Required (sorry for SK but previous task for this was written in EN) Show this particular data in bottom sheet after clicking on point detail:

Version: 1.0.6 (34)

Parkomat: lokalita, ID parkomatu, (budúcnosť chceme vkladať do detailu odkaz na návod ako používať parkomaty) fáza 100
Partnerské prevádzky: Názov, adresa, otváracie hodiny
Garáže: Názov, Prevádzková doba, Adresa, informácia NPK(sk)(en) + informácia RPK(sk)(en)
Parkoviská: Názov, prevádzková doba, počet parkovacích miest, spoje MHD, vzdialenosť MHD, dojazdová doba MHD do centra
P+R: Názov, prevádzková doba, počet parkovacích miest, spoje MHD, vzdialenosť MHD, dojazdová doba MHD do centra

FIGMA - mapa zón PAAS : https://www.figma.com/file/Wv7IU3KeHl7vJeAUxp8461/Mestsk%C3%A9-mapy?type=design&node-id=277-2514&mode=design&t=3Ug5IcFn3GZFvIdu-0

Doplňujúcim taskom je doplnenie novej kategórie: Podpora s vrstvou ktorá obsahuje body s klientskymi miestami aka ,,Pobočky,, dizajn ikonky: https://www.figma.com/file/Wv7IU3KeHl7vJeAUxp8461/Mestsk%C3%A9-mapy?type=design&node-id=277-2514&mode=design&t=3Ug5IcFn3GZFvIdu-0
Doplnenie klientskych miest: názov, adresa, otváracie hodiny, miesto

Current state:

![Image](https://github.com/bratislava/paas-mpa/assets/108303461/ecf99558-b0d8-43d1-8a09-75b81bd6537f)

**Comment by PavelFilo** [comment]
works on my machine ;) both on android and iphone and I cannot reproduce it

**Comment by zuzanaslobodova** [comment]
Hello Pali, it is not working on mine iPhone 14PRO. Stop by in the afternoon please :) and we will check
