### ISSUE TITLE
I bought approx 2,5 hours in tickets with 2 hour bonus card for free

### ISSUE THREAD

**Issue by PavelFilo** [bratislava/paas-mpa#428]
I have bonus card (2 hours per day)

I bought 17 min ticket with bonus card in one zone, then prolongated it to 15 more minutes and afterwards it enabled me to buy new 2h ticket with same bonus card on the same ecv in different zone...   

And it enables me to buy even more tickets

Environment: staging

![Image](https://github.com/bratislava/paas-mpa/assets/61841194/e63f98f7-51d4-45c2-bfb1-012867c02795)
![IMG_3383](https://github.com/bratislava/paas-mpa/assets/61841194/8f792f9e-f062-4c1f-87eb-b8bac76a5074)
![IMG_3382](https://github.com/bratislava/paas-mpa/assets/61841194/253bea6b-e42e-40e0-80ed-65b7e9a9e05f)

**Comment by radoslavzeman** [comment]
Na stagingu parkdotsu nefunguje vraj odravanie z bonusovych kariet aktualne.
