### ISSUE TITLE
Mapa a pin na mape

### ISSUE THREAD

**Issue by zuzanaslobodova** [bratislava/paas-mpa#458]
iOS users feedback:

1. v mape občas nepresne ukazuje polohu, je to síce v rámci jednej zóny, ale namiesto Kadnárova ulica ukazuje Černockého ulicu
2. Zlá lokalizacia, iba som navigovala pohybom prsta . Metodova nemoze byt v susedstve s Vajnorskou
3. Pri zobrazenej mape PINu, ktory zobrazuje polohu sa mi obcas (odhad 50%, nie vzdy) dialo, ze ked som „zapichol“ PIN, aby som nastavil parkovacie miesto, tak po dvihnuti prsta sa mi PIN posunul (vacsinou dolava, nepamatam, ze by sa posunul niekedy doprava) – pri kraji zony sa mi stalo aj to, ze sa posunul z jednej zony do druhej, ktora bola vedla...

Android user feedback:
1. po zadaní kódu úseku parkovania, napríklad 2005 Záhradnícka stred alebo 3005 Vajnorská sa pin nepresunie na daný úsek, ale vedľa neho.

Želaný stav: nech sa pin nehýbe, nech ostane tam, kde ho user zapichne. Pin nech sa zhoduje a adresou v poli, kde je zobrazená adresa 1:1

Screenshots a viac info: v tabulke s feedbackom a konkretne ID 1, ID 7: https://magistratba.sharepoint.com/:x:/r/sites/InnovationTeam/_layouts/15/Doc.aspx?sourcedoc=%7B9D6A6BF4-D1C7-4BE6-86C7-886D4909E4E9%7D&file=Feedback%20z%20testovania.xlsx&action=default&mobileredirect=true,

**Comment by PavelFilo** [comment]
tried my best, but I cannot reproduce any of the issues mentioned above. Tried small iOS, big iOS, big text in iOS, also small Android device and there was no issue whatsoever... setting to `On Hold` for now
