### ISSUE TITLE
Android Bottomsheet fails

### ISSUE THREAD

**Issue by zuzanaslobodova** [bratislava/paas-mpa#475]
Na Androidoch sa na mape (main page) nezobrazuje bottomsheet a tým pádom je zmenožnený nákup parkovacieho lístka. 

Želaný stav: Bottomsheet nech je zorbazený a user si môže kliknúť na "Pokračovať"

**Comment by zuzanaslobodova** [comment]
@PavelFilo nezreprodukované na našom Androide :(

**Comment by zuzanaslobodova** [comment]
Userovi pomohlo si appku natvrdo vypnúť a zapnúť. Potom už išlo. Myslím, že by bolo dobré ďalej aktívne zisťovať, kde je príčina tohto problému.

**Comment by PavelFilo** [comment]
Added `onClose={localRef.current?.expand}` and this hopefully fixes the problem
