### ISSUE TITLE
Oneskorený lístok

### ISSUE THREAD

**Issue by zuzanaslobodova** [bratislava/paas-mpa#484]
Case 1:
kupili sme listok na KO123OK v ruzinove, skratili ho a mal platit este do 12:15. Hned nato sme kupili listok v SM na AA123XX. Akonahle bol vydany tento novy listok, nikde mi nezobrazuje ten povodny, ktory este mal platit. Nie je v aktivnych ani historii. 
pri skracovani dava appka info - posledny bod je cca, ze pri skracovani predlzeneho listka, sa skrati iba to posledne predlzenie - skratilo mi ho vsak hned a uplne, aj do toho povodneho casu (cize na zacatie parkovania + 15min). 
uz mi zmizol aj listok pre AA123XX, nie je ani v historii

Case 2: 
Keď si kúpim lístok, a už sa ukončí, nezobrazí sa v Histórii hneď, musím najprv zatvoriť a znovu otvoriť aplikáciu.​

Príklad – mal som lístok pre Staré Mesto – STU do 11:21 (obrázok 2 vedľa), no ešte o 11:49 mi ho v Histórii neukazovalo (obrázok 1). Keď som zatvoril a znovu otvoril aplikáciu, lístok už v Histórii ukázalo (obrázok 2 – čas 11:50). 

Case 3: 
kupil som listok, od 9:17 do 12:30, nasledne som ho skratil a zavolal tento request https://paas-mpa-backend.bratislava.sk/tickets?parkingEndFrom=2024-05-02T07%3A20%3A29.925Z listok mi vratilo... po chvilke som zavolal ten isty request s novym casom (cca 9:27) a uz mi skrateny listok neprisiel (listok po skrateni mal trvat do 12:15) bola to zona kde sa plati od 12:00... podla mna je to zreprodukovatelne na vsetkych zonach, aj ked si kupujes listok kde sa plati hned...

**Comment by PavelFilo** [comment]
case 1 je podla threadu v slacku zelany efekt... 
case 2 v ticketoch je refresh ked potiahne user dodola alebo sa vrati do menu a spat na tickety
case 3 rovnako ako 1 zelany efekt
