### ISSUE TITLE
Link na Privacy policy v EN

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/paas-mpa#489]
Main menu > Privacy policy (je aktualne prelink na slovenskú verziu, prosim updatnut na EN: https://paas.sk/en/privacy-policy/)

**Comment by zuzanaslobodova** [comment]
Prosím @radoslavzeman ešte tieto dve:

Terms&Conditions ma existujucu urlku v anglickej verzii stranky, ale ano, je na nej text po slovensky.
https://paas.sk/en/terms-of-use/

Kontakt tiez existuje v EN: https://paas.sk/en/contact/
