### ISSUE TITLE
Zapísanie lístka do DB

### ISSUE THREAD

**Issue by zuzanaslobodova** [bratislava/paas-mpa#491]
Kúpila som lístok 2.5. s Apple pay, a nemám ho medzi aktívnymi a nie je ani na mape vľavo dole. Peniaze odišli. Listok v metabase nemám. 

Detaily: EČV "zuzkas" čas nákupu 15:50 a duration je 30 min.
Update 2.5.: o 15:56 som vypla a zapla appku, lístok už bol medzi aktívnymi aj dole vľavo. V Metabase ho stále nevidím. UDR 2026 Ružinov

Update 7.5.: v Metabase lístok nie je zapísaný

**Comment by pkulcsarnr** [comment]
Result: Metabase displays the raw dates from the database at the moment, which is UTC. The ticket was in metabase, but was not easily recognized as the correct one because of the date difference.
