### ISSUE TITLE
Add type for Social Services card in BE

### ISSUE THREAD

**Issue by radoslavzeman** [bratislava/paas-mpa#637]
The Social Services card is missing in `ParkingCardType`

![Image](https://github.com/user-attachments/assets/961fdf5a-cbb6-471a-9809-acae6cd34d58)

**Comment by zuzanaslobodova** [comment]
Peťo K. preverí, či nám Sociálna karta už z Parkdotsu náhodou nechodí ako Other.

**Comment by zuzanaslobodova** [comment]
@pkulcsarnr 

Info ku karte: tak ano je tam 90% zlava. je to viazane na kontkrentu ECV a ty na nu vies kupovat ak mas socialnu kartu s tou 90% zlavou ..
