### ISSUE TITLE
Apple Live Activities

### ISSUE THREAD

**Issue by PavelFilo** [bratislava/paas-mpa#662]

**Comment by zuzanaslobodova** [comment]
![Image](https://github.com/user-attachments/assets/0181eb87-7a1e-412c-a826-d3381c7e8a63)
![Image](https://github.com/user-attachments/assets/d48b64ed-f45e-4c95-b8b2-ad31bd7a7b91)

Po skončení parkovacieho lístku mi ostala takto zaseknutá Live Activity - na zamknutom screene aj na odomknutom. PAAS appku som niekolko krát swipe-upla a nepomohlo. Až večer som zistila, že potiahnutím live activity na zamknutom screene doľava sa dá vymazať. Až toto vymazanie ju dalo preč.
